-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 21:04:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema verdureiraCrud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema verdureiraCrud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verdureiraCrud` DEFAULT CHARACTER SET utf8 ;
USE `verdureiraCrud` ;

-- -----------------------------------------------------
-- Table `verdureiraCrud`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdureiraCrud`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NOT NULL,
  `tamanho` VARCHAR(40) NOT NULL,
  `cor` VARCHAR(40) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdureiraCrud`.`Verdureira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdureiraCrud`.`Verdureira` (
  `idVerdureira` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idVerdureira`),
  INDEX `fk_Verdureira_Produto_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Verdureira_Produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `verdureiraCrud`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE verdureiraCrud;
